// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';


var bookshelfs = /* :: */[
  /* record */[
    /* title */"Currently Reading",
    /* key */"currentlyReading"
  ],
  /* :: */[
    /* record */[
      /* title */"Want To Read",
      /* key */"wantToRead"
    ],
    /* :: */[
      /* record */[
        /* title */"Read",
        /* key */"read"
      ],
      /* [] */0
    ]
  ]
];

exports.bookshelfs = bookshelfs;
/* No side effect */
