// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var RR$ReactTemplate = require("../RR.bs.js");
var BookContent$ReactTemplate = require("../components/BookContent.bs.js");

var api = "https://reactnd-books-api.udacity.com";

var fetchWithHeader = fetch("https://reactnd-books-api.udacity.com/books", Fetch.RequestInit[/* make */0](/* Get */0, {
            Accept: "application/json",
            Authorization: "myreadrelocal123123"
          }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0));

var component = ReasonReact.reducerComponent("Home");

function make(updatePage, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              return Curry._1(self[/* send */3], /* FetchBooks */0);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* books */0];
              var booksContent;
              if (match !== undefined) {
                var books = Js_primitive.valFromOption(match).books;
                booksContent = ReasonReact.element(undefined, undefined, BookContent$ReactTemplate.make(books, /* array */[]));
              } else {
                booksContent = null;
              }
              return React.createElement("div", {
                          className: "home"
                        }, React.createElement("div", {
                              className: "list-books"
                            }, React.createElement("div", {
                                  className: "list-books-title"
                                }, React.createElement("h1", undefined, RR$ReactTemplate.string("MyReads")), React.createElement("p", undefined, RR$ReactTemplate.string("Udacity React nanodegree MyReads project")), React.createElement("button", {
                                      className: "btn",
                                      onClick: (function () {
                                          return Curry._1(updatePage, /* () */0);
                                        })
                                    }, RR$ReactTemplate.string("Add a book")))), booksContent);
            }),
          /* initialState */(function () {
              return /* record */[/* books */undefined];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* books */Js_primitive.some(action[0])]]);
              } else {
                return /* UpdateWithSideEffects */Block.__(2, [
                          state,
                          (function (self) {
                              fetchWithHeader.then((function (prim) {
                                        return prim.json();
                                      })).then((function (item) {
                                      return Promise.resolve(Curry._1(self[/* send */3], /* UpdateBooks */[item]));
                                    }));
                              return /* () */0;
                            })
                        ]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.api = api;
exports.fetchWithHeader = fetchWithHeader;
exports.component = component;
exports.make = make;
/* fetchWithHeader Not a pure module */
