// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var RR$ReactTemplate = require("../RR.bs.js");

var component = ReasonReact.statelessComponent("Home");

function make(updatePage, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "home"
                        }, React.createElement("div", {
                              className: "list-books"
                            }, React.createElement("div", {
                                  className: "list-books-title"
                                }, React.createElement("h1", undefined, RR$ReactTemplate.string("MyReads")), React.createElement("p", undefined, RR$ReactTemplate.string("Udacity React nanodegree MyReads project")), React.createElement("div", {
                                      className: "btn",
                                      onClick: Curry._1(updatePage, "/search")
                                    }, RR$ReactTemplate.string("Add a book")))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
