// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var RR$ReactTemplate = require("../RR.bs.js");

var component = ReasonReact.statelessComponent("BookList");

function make(book, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var style = {
                backgroundImage: "url(" + (book[/* imageLinks */7][/* smallThumbnail */0] + ")"),
                height: "193px",
                width: "128px"
              };
              return React.createElement("li", undefined, React.createElement("div", {
                              className: "book"
                            }, React.createElement("div", {
                                  className: "book-top"
                                }, React.createElement("div", {
                                      className: "book-cover",
                                      style: style
                                    }), React.createElement("div", {
                                      className: "book-shelf-changer"
                                    })), React.createElement("div", {
                                  className: "book-title"
                                }, RR$ReactTemplate.string(book[/* title */16])), React.createElement("div", {
                                  className: "book-authors"
                                }, $$Array.of_list(List.map((function (author) {
                                            return React.createElement("span", {
                                                        key: author
                                                      }, RR$ReactTemplate.string(author));
                                          }), book[/* authors */1])))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
