// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("BookContent");

function make(books, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var booksComponent = function (book) {
                var style = {
                  backgroundImage: "url(" + (book.imageLinks.smallThumbnail + ")"),
                  height: "193px",
                  width: "128px"
                };
                return React.createElement("li", undefined, React.createElement("div", {
                                className: "book"
                              }, React.createElement("div", {
                                    className: "book-top"
                                  }, React.createElement("div", {
                                        className: "book-cover",
                                        style: style
                                      }), React.createElement("div", {
                                        className: "book-shelf-changer"
                                      })), React.createElement("div", {
                                    className: "book-title"
                                  }, book.title), React.createElement("div", {
                                    className: "book-authors"
                                  }, book.author)));
              };
              return React.createElement("div", {
                          className: "list-books-content"
                        }, React.createElement("div", {
                              className: "bookshelf"
                            }, React.createElement("h2", {
                                  className: "bookshelf-title"
                                }, React.createElement("span", undefined, "books")), React.createElement("div", {
                                  className: "bookshelf-books"
                                }, React.createElement("ol", {
                                      className: "books-grid"
                                    }, $$Array.map(booksComponent, books)))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
