// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");

function string(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

var element = ReasonReact.element;

exports.string = string;
exports.array = array;
exports.element = element;
/* ReasonReact Not a pure module */
